### ISSUE TITLE
Checklist of things for CES module

### ISSUE THREAD

**Issue by simonrolph** [BioDT/biodt-shiny#73]
Just some quick notes for myself:

- [x]  Check colour scheme for recreation potential model, Chris back
- [x] topography map layer
- [x] Colour scales
- [ ] Review species - run more models
- [x] Map computation issues
- [x] Disclaimer
- [x] Why don't plants work - remove map moving functionality

Further tasks:
- [ ] Highlight only areas of a binned RP level
- [ ] - [ ] Remove twinflower

**Comment by simonrolph** [comment]
Will be split into separate issues
